repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.12.0
    hooks:
      - id: isort
        name: isort
        args: ["--settings-path", "pyproject.toml"]

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        name: black
        args: ["--config", "pyproject.toml"]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.261
    hooks:
      - id: ruff
        name: ruff
        args: ["--config", "pyproject.toml"]