[project]
name = "exam-tutor"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "async-sqlalchemy>=1.0.0",
    "black>=24.10.0",
    "isort>=5.13.2",
]
