"""array links

Revision ID: 0c937105a8fd
Revises: 814280eb7df1
Create Date: 2025-01-04 11:43:46.523297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c937105a8fd'
down_revision: Union[str, None] = '814280eb7df1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('task_sound_links', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('tasks', sa.Column('task_file_links', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('tasks', sa.Column('task_photo_links', sa.ARRAY(sa.String()), nullable=True))
    op.drop_column('tasks', 'task_file_link')
    op.drop_column('tasks', 'task_photo_link')
    op.drop_column('tasks', 'task_sound_link')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('task_sound_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('task_photo_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('task_file_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'task_photo_links')
    op.drop_column('tasks', 'task_file_links')
    op.drop_column('tasks', 'task_sound_links')
    # ### end Alembic commands ###
