"""task

Revision ID: 814280eb7df1
Revises: 3255b3a99fb8
Create Date: 2024-12-25 22:49:22.826242

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "814280eb7df1"
down_revision: Union[str, None] = "3255b3a99fb8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tasks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("exam", sa.Enum("EGE", "OGE", name="examenum"), nullable=False),
        sa.Column(
            "subject",
            sa.Enum(
                "MATH",
                "INFORMATICS",
                "RUSSIAN",
                "ENGLISH",
                "GERMAN",
                "FRENCH",
                "SPANISH",
                "PHYSICS",
                "CHEMISTRY",
                "BIOLOGY",
                "GEOGRAPHY",
                "SOCIAL",
                "LITERATURE",
                "HISTORY",
                name="subjectenum",
            ),
            nullable=False,
        ),
        sa.Column(
            "exam_task_number",
            sa.Enum(
                "ONE",
                "TWO",
                "THREE",
                "FOUR",
                "FIVE",
                "SIX",
                "SEVEN",
                "EIGHT",
                "NINE",
                "TEN",
                "ELEVEN",
                "TWELVE",
                "THIRTEEN",
                "FOURTEEN",
                "FIFTEEN",
                "SIXTEEN",
                "SEVENTEEN",
                "EIGHTEEN",
                "NINETEEN",
                "TWENTY",
                "TWENTY_ONE",
                "TWENTY_TWO",
                "TWENTY_THREE",
                "TWENTY_FOUR",
                "TWENTY_FIVE",
                "TWENTY_SIX",
                "TWENTY_SEVEN",
                "TWENTY_EIGHT",
                "TWENTY_NINE",
                "THIRTY",
                name="examtasknumber",
            ),
            nullable=False,
        ),
        sa.Column("condition", sa.String(), nullable=False),
        sa.Column("answer", sa.String(), nullable=False),
        sa.Column(
            "difficult",
            sa.Enum("EASY", "MIDDLE", "HARD", name="difficultenum"),
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("find_code", sa.String(), nullable=False),
        sa.Column("task_sound_link", sa.String(), nullable=True),
        sa.Column("task_file_link", sa.String(), nullable=True),
        sa.Column("task_photo_link", sa.String(), nullable=True),
        sa.Column("answer_video_link", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tasks")
    # ### end Alembic commands ###
