"""init2

Revision ID: 8db3917df319
Revises: 3255b3a99fb8
Create Date: 2024-12-22 22:38:58.748128

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8db3917df319"
down_revision: Union[str, None] = "3255b3a99fb8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "answer_videos",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("link", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "task_files",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("link", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "task_photos",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("link", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "task_sounds",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("link", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("exam", sa.Enum("EGE", "OGE", name="examenum"), nullable=True),
        sa.Column(
            "subject",
            sa.Enum(
                "MATH",
                "INFORMATICS",
                "RUSSIAN",
                "ENGLISH",
                "GERMAN",
                "FRENCH",
                "SPANISH",
                "PHYSICS",
                "CHEMISTRY",
                "BIOLOGY",
                "GEOGRAPHY",
                "SOCIAL",
                "LITERATURE",
                "HISTORY",
                name="subjectenum",
            ),
            nullable=True,
        ),
        sa.Column(
            "exam_task_number",
            sa.Enum(
                "ONE",
                "TWO",
                "THREE",
                "FOUR",
                "FIVE",
                "SIX",
                "SEVEN",
                "EIGHT",
                "NINE",
                "TEN",
                "ELEVEN",
                "TWELVE",
                "THIRTEEN",
                "FOURTEEN",
                "FIFTEEN",
                "SIXTEEN",
                "SEVENTEEN",
                "EIGHTEEN",
                "NINETEEN",
                "TWENTY",
                "TWENTY_ONE",
                "TWENTY_TWO",
                "TWENTY_THREE",
                "TWENTY_FOUR",
                "TWENTY_FIVE",
                "TWENTY_SIX",
                "TWENTY_SEVEN",
                "TWENTY_EIGHT",
                "TWENTY_NINE",
                "THIRTY",
                name="examtasknumber",
            ),
            nullable=True,
        ),
        sa.Column("condition", sa.String(), nullable=True),
        sa.Column("answer", sa.String(), nullable=True),
        sa.Column(
            "difficult",
            sa.Enum("EASY", "MIDDLE", "HARD", name="difficultenum"),
            nullable=True,
        ),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("task_sound_id", sa.UUID(), nullable=False),
        sa.Column("task_file_id", sa.UUID(), nullable=False),
        sa.Column("task_photo_id", sa.UUID(), nullable=False),
        sa.Column("answer_video_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["answer_video_id"],
            ["answer_videos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_file_id"],
            ["task_files.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_photo_id"],
            ["task_photos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_sound_id"],
            ["task_sounds.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tasks")
    op.drop_table("task_sounds")
    op.drop_table("task_photos")
    op.drop_table("task_files")
    op.drop_table("answer_videos")
    # ### end Alembic commands ###
